### ISSUE TITLE
requirements.txt need update

### ISSUE THREAD

**Issue by congtan97** [udacity/cd0046-SQL-and-Data-Modeling-for-the-Web#10]
I try to run
pip install -r requirements.txt
has an error:
ImportError: cannot import name 'Markup' from 'jinja2'

(I'm using Windows)

**Comment by SudKul** [comment]
@congtan97 Please suggest a fix in a PR or discuss this issue on the https://knowledge.udacity.com/ platform with our experienced mentors.
