### ISSUE TITLE
Incomplete dependencies

### ISSUE THREAD

**Issue by SalmanuRidwan** [udacity/cd0046-SQL-and-Data-Modeling-for-the-Web#3]
The requirements.txt contains failed dependencies. The version of flask_moment provided isn't compatible with jinja2 as an ImportError is returned with message ```ImportError: cannot import name 'Markup' from 'jinja2'```

**Comment by ajimoti** [comment]
Same error @SalmanuRidwan were you able to solve this?

**Comment by horatiothomas** [comment]
Just update the dependencies in requirements.
