### ISSUE TITLE
Requirments.txt

### ISSUE THREAD

**Issue by rodrickcalvin** [udacity/cd0046-SQL-and-Data-Modeling-for-the-Web#9]
Please update the requirements.txt and the required imports in different files to be in line with the latest needs for the latest python. In addition, consider a setup with poetry that runs on top of pip.

**Reasons:**
- Some of the libraries imported are deprecated.

**Comment by SudKul** [comment]
@rodrickcalvin 
Please suggest a fix in a PR or discuss this issue on the https://knowledge.udacity.com/ platform with our experienced mentors.
